# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 235348634a5fac5335bbc56c3b1d0162ad694a5dfef545be6e9e0733f30b622b3edeaff02ddb041ae7478e3dfe9981f2f296e2c58e42c2383c81c68000143e53

test:
  secret_key_base: 7f274127e0c5681acbb7d0dd69a258442f0378ee6d484dfb38294ec16ca6352cd4eede88039bbe947b5f4a043fc26cc1087734cf09b1bd42de1ba78e23d4a6b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
